# Generated by Django 4.0.2 on 2022-02-05 03:20

from django.db import migrations, models
import django.db.models.deletion
import roles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('groups', models.ManyToManyField(related_name='role_groups', to='auth.Group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', roles.models.RoleManager()),
            ],
        ),
    ]
