# Generated by Django 4.0.3 on 2022-03-07 14:52

from django.db import migrations, models
from django.utils import timezone

from roles.models import Role


def set_codename(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    # create a group for firebase functions that permissions can be added to
    MigrationRole = apps.get_model("roles", "Role")
    for role in MigrationRole.objects.using(db_alias).all():
        Role.set_codename(role)
        role.save()


def unset_codename(apps, schema_editor):
    pass


def timestamp():
    return str(timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="codename",
            field=models.CharField(default=timestamp, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_codename, unset_codename),
    ]
