# Generated by Django 4.0.3 on 2022-03-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0002_role_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='groups',
            field=models.ManyToManyField(related_name='roles', to='auth.group'),
        ),
    ]
