"""
Django settings for bltestproject project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
from baseline.settings import *

ROOT_URLCONF = "bltestproject.urls"
WSGI_APPLICATION = "bltestproject.wsgi.application"
