# add project-specific variables here
ENVIRONMENT
SENTRY_DSN
# baseline variables below; do not edit
CELERY_BROKER_URL
CELERY_RESULT_BACKEND
DATABASE_URL
DJANGO_ALLOWED_HOSTS
DJANGO_DEBUG
DJANGO_SECRET_KEY
DJANGO_SETTINGS_MODULE
REDIS_CACHE_URL
