#!/bin/bash

# bail on first failure
set -e

SCRIPT_DIR=$(dirname $0)
PYTHON=${PYTHON:-python}

# make sure we are at the project root
cd ${SCRIPT_DIR}/..

# set a secret key
export DJANGO_SECRET_KEY=django_test_run

exec ${PYTHON} manage.py test_my_apps
