# Generated by Django 4.0.2 on 2022-02-23 22:32

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ("bltestapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    django_fsm.FSMField(
                        choices=[("new", "new"), ("done", "done"), ("error", "error")],
                        default="new",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
